AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DeploymentVersion:
    Type: String
    Default: "4"
  DatabaseUrl:
    Type: String
    Default: "postgresql://postgres:%23Alexander94@shining-smiles-db.cxu2ww2uu37o.us-east-2.rds.amazonaws.com:5432/shining_smiles"
  VerifyToken:
    Type: String
    Default: "shiningsmiles_verify_2025"
  SecretArn:
    Type: String
    Default: "arn:aws:secretsmanager:us-east-2:596814071505:secret:shining-smiles-db-credentials-CskeX3"

Resources:
  ShiningSmilesWebhook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: webhook_handler.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Layers:
        - arn:aws:lambda:us-east-2:596814071505:layer:shining-smiles-deps-layer:17
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          WHATSAPP_VERIFY_TOKEN: !Ref VerifyToken
          DEPLOYMENT_VERSION: !Ref DeploymentVersion
          SECRET_ARN: !Ref SecretArn
          SMS_API_BASE_URL: "http://31.187.76.42/api"
          SMS_API_KEY: "iinOd1le.Q6sAq9GDBSpFH0rMKeqbdeVsweIrMnnc"
          WHATSAPP_CLOUD_API_TOKEN: "EAAQcV6fZC5GABPeFwno1m6ZCsZAfXMtzhp1PwOZAv4RaXaSI1cMEKn6bMS8DI6hIYyGIPgaX6G0h00IDgZAREytSWcMh0yHF7PucK2mmMfvHqzPkaNDIxfpIBHOPqyC5wnwZANZCBoS2n1wr2J5ZBZB0iDyzh4I8R4HLa7pmVDw1Hz4lgmulbOYvVFEQMR7uXYZAWWAZDZD"
          WHATSAPP_CLOUD_NUMBER: "1296681201995738"
          APP_BASE_URL: "https://api.shiningsmilescollege.ac.zw"
          FLASK_ENV: "production"
          LOG_LEVEL: "DEBUG"
      Events:
        Webhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: any
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref SecretArn
    Metadata:
      BuildMethod: python3.11